Vim: Solves an issue which causes Vim to exit with non zero exit code
Git and crontab complained about vi. Git showed this error message

> error: There was a problem with the editor 'vi'

It turns out that [Vim was exiting with non zero error
code](http://tooky.co.uk/2010/04/08/there-was-a-problem-with-the-editor-vi-git-on-mac-os-x.html).

This fix from [a comment on the
article](http://tooky.co.uk/2010/04/08/there-was-a-problem-with-the-editor-vi-git-on-mac-os-x.html#comment-87526162)
fixes the issue.